version: '3.8'

services:
  app:
    build: .
    container_name: taux-app
    restart: always
    expose:
      - "8080"

  nginx:
    image: nginx:alpine
    container_name: taux-website
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static/502.html:/usr/share/nginx/html/errors/502.html:ro
      - ./static/503.html:/usr/share/nginx/html/errors/503.html:ro
    depends_on:
      - app
