# Dockerfile.dev
FROM golang:1.24-alpine

WORKDIR /app

RUN go install github.com/air-verse/air@latest
RUN go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

COPY . .

RUN go mod tidy

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
