// Reports paths that were published once and are no longer reachable.
//
//   node scripts/check-routes.js          verify
//   node scripts/check-routes.js --record  add today's paths to the ledger
//
// main.rs tells the next person that "retiring a path is allowed; retiring it
// silently is not — declare the old path under [[redirect]] and the contract
// test will hold you to it." That was not true when it was written. The
// contract test asserts the redirects somebody remembered to declare; it has
// no way to notice one that was never declared, because every gate in this
// repository is driven from the current site.toml and none of them remembers
// what used to be in it. Delete a `path` and forget the `[[redirect]]` and all
// of them stay green while an indexed URL starts answering 404 — a failure
// whose only witnesses are people following a link that used to work.
//
// This is the missing memory. published-paths.txt is a build artifact under
// version control, the same arrangement styles.min.css already has: generated
// by a command, committed, and checked for freshness so it cannot drift from
// what it describes.
//
// Two assertions, and they are deliberately in opposite directions:
//
//   every current page is in the ledger    — so a new route gets recorded
//   every ledger path still resolves       — as a page, or as a redirect
//
// The first is what makes the second trustworthy. Without it the ledger would
// only ever describe whichever paths existed on the day somebody remembered to
// run the command.
//
// Git history was the other candidate and was rejected: this repository has
// already been bitten once by CI and Cloudflare cloning shallowly, which is
// what made deriving dates from commits unreliable. A check that reads the
// working tree cannot be undone by a clone depth.

const fs = require("fs");
const path = require("path");
const { parse } = require("smol-toml");

const ROOT = path.join(__dirname, "..");
const SITE = path.join(ROOT, "site.toml");
const LEDGER = path.join(ROOT, "published-paths.txt");

const HEADER = `# Every path this site has ever published, one per line.
#
# Generated by \`npm run routes:record\` and checked by \`npm run check:routes\`.
# Entries are never removed: the file's whole purpose is to remember paths that
# site.toml no longer mentions, so that retiring one without a redirect fails
# the build instead of silently 404ing a URL somebody already linked to.
#
# Adding a page? Run the record command and commit the result.
# Removing one? Add a [[redirect]] in site.toml pointing it somewhere real.
`;

function readSite() {
  const site = parse(fs.readFileSync(SITE, "utf8"));
  return {
    paths: (site.page || []).map((p) => p.path),
    redirects: new Set((site.redirect || []).map((r) => r.from)),
  };
}

function readLedger() {
  if (!fs.existsSync(LEDGER)) return null;
  return fs
    .readFileSync(LEDGER, "utf8")
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l && !l.startsWith("#"));
}

function record() {
  const { paths } = readSite();
  const existing = readLedger() || [];
  // Union, never a replacement. Rewriting the file from site.toml alone would
  // erase exactly the history this exists to keep.
  const all = [...new Set([...existing, ...paths])].sort();
  fs.writeFileSync(LEDGER, HEADER + all.join("\n") + "\n");
  const added = all.filter((p) => !existing.includes(p));
  console.log(
    added.length
      ? `\nrecorded ${added.length} new path(s):\n${added.map((p) => `      ${p}`).join("\n")}`
      : "\nledger already lists every current path"
  );
}

function verify() {
  const { paths, redirects } = readSite();
  const ledger = readLedger();

  if (ledger === null) {
    console.log("\npublished-paths.txt is missing — run npm run routes:record and commit it.");
    process.exitCode = 1;
    return;
  }

  const unrecorded = paths.filter((p) => !ledger.includes(p));
  // A ledger path is still honoured if it is a live route, or if something
  // redirects away from it. Whether the redirect lands anywhere real is the
  // contract test's job — it is the one that can actually make a request.
  const abandoned = ledger.filter((p) => !paths.includes(p) && !redirects.has(p));

  if (unrecorded.length) {
    console.log("\n  unrecorded — published but absent from the ledger\n");
    for (const p of unrecorded) console.log(`      ${p}`);
    console.log("\n  Run npm run routes:record and commit published-paths.txt.");
  }

  if (abandoned.length) {
    console.log("\n  retired silently — no longer a route and nothing redirects from it\n");
    for (const p of abandoned) console.log(`      ${p}`);
    console.log(
      "\n  Every one of these was published and may be linked to or indexed." +
        "\n  Add a [[redirect]] in site.toml pointing each at where it went."
    );
  }

  if (unrecorded.length || abandoned.length) {
    process.exitCode = 1;
    return;
  }

  console.log(
    `\nevery published path still resolves (${paths.length} live, ` +
      `${ledger.length - paths.length} retired via redirect)`
  );
}

process.argv.includes("--record") ? record() : verify();
