// Korean typographic decisions, as a ledger rather than a rule.
//
// TWO KINDS TODAY, and the name of this file is deliberately not either of
// them. It began as `check-ko-spacing.js`, then issue #240 added quotation
// marks and the name would have been half-true from that day on — this repo has
// been bitten three times by a description that stopped matching what it
// described (NOTES.md opens with the count). `check:ko` says "the Korean
// ledger" and stays true when a third kind arrives.
//
//   1. WORD SPACING across an inline tag boundary  ->  ko-spacing.txt
//   2. WHICH QUOTATION MARK a passage uses         ->  ko-quotes.txt
//
// WHY NEITHER IS A RULE. Both need semantics, not pattern matching.
//
// Spacing: Korean 띄어쓰기 across a tag boundary decides by what the syllable
// is, not what it looks like:
//
//   </strong>가        particle — glued, correct
//   </strong>가능한    content word — needs a space
//
// Quotes: the same passage takes a different mark by what it IS. PR #237 went
// through 301 of them by hand and the three answers were direct speech -> "",
// terms and emphasis -> '', names of regulations and sections -> 「」. Issue
// #242 then added a fourth: independently published documents -> 『』. No
// pattern separates a quoted sentence from a quoted term.
//
// A character-level rule gets both jobs wrong, and a checker that raises
// judgement calls gets switched off. This repo has already written that down
// about `i18n-extract`: a tool that fails the build on a judgement call is a
// tool someone disables.
//
// SO IT REMEMBERS INSTEAD OF DECIDING. Every boundary and every quoted passage
// a person has looked at is recorded with the decision they made. The check
// speaks only when one changes or a new one appears — both of which mean a
// human should look, and neither of which is the tool having an opinion about
// Korean.
//
// Same shape as published-paths.txt: the ledger is the memory, the check is the
// comparison, and `--record` is how a decision enters it.
//
// WHAT IT CANNOT DO, said plainly: it does not know whether the recorded
// decisions are right. It knows they were made. The 175 boundaries in PR #227
// and the 301 quotes in PR #237 were judged by hand against a rendered-text
// reading, and this file inherits that judgement wholesale. It guards
// regressions and flags new pages; it is not a proofreader.
//
// Usage:
//   node scripts/check-ko.js            compare against both ledgers
//   node scripts/check-ko.js --record   write today's decisions

const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.join(__dirname, "..");
const DIR = path.join(ROOT, "templates", "ko-KR");
const SPACING = path.join(ROOT, "ko-spacing.txt");
const QUOTES = path.join(ROOT, "ko-quotes.txt");

const SPACING_HEADER = `# Every Korean word boundary that touches an inline tag, and whether a person
# left a space there.
#
# Generated by \`npm run ko:record\` and checked by \`npm run check:ko\`.
#
# Korean particles attach to the preceding word with no space (\`</code>를\`);
# content words take one (\`아니라 <strong>\`). Which one a syllable is cannot be
# decided by pattern, so this file records what a person decided rather than
# what a rule would say.
#
# A changed line means a boundary moved — read it and re-record if it is right.
# A new line means a page arrived that nobody has proofread yet.
`;

const QUOTES_HEADER = `# Every quoted passage on the Korean pages, and which mark a person put around
# it.
#
# Generated by \`npm run ko:record\` and checked by \`npm run check:ko\`.
#
# The second column is the pair itself. PR #237 judged 301 of these one at a
# time and issue #242 settled the fourth kind:
#
#   ""    direct speech, quoted sentences
#   ''    terms, concepts, emphasis
#   「」  names of regulations, policy items, section headings
#   『』  independently published documents — guidelines, books, reports
#   “”    the same as "" but written with &ldquo;/&rdquo;
#   ‘’    the same as '' but written with &lsquo;/&rsquo;
#
# THE LAST TWO ARE THE SAME DECISION SPELLED DIFFERENTLY, and they are recorded
# as their own kind so that a change of spelling is visible rather than
# invisible. It is not by itself a mistake: today's two are the home page's
# pull quotes, and all five locales write those with &ldquo; — so the ledger
# shows the difference and says nothing about it. Nothing here says which mark
# belongs where either; that needs to know whether a passage is speech or a
# term, and no pattern can tell.
#
# A changed line means a mark changed or the text inside it did. A new line
# means a passage nobody has proofread yet.
`;

// Tags whose own layout already separates the words, so the source looking
// glued says nothing about how it reads. Judged on the rendered result during
// the PR #227 pass; kept here so the ledger does not fill with non-boundaries.
const SEPARATED = /\b(?:block|flex|grid|mr-\d|ml-\d|gap-\d|eyebrow)\b/;

function boundaries(html) {
  const body = html.replace(/<!--[\s\S]*?-->/g, "");
  const out = [];
  // A closing tag followed by hangul, or hangul followed by an opening tag.
  const re = /(<\/(?:strong|code|a|em|span|abbr)>)(\s?)([가-힣])|([가-힣])(\s?)(<(?:strong|code|a|em|span|abbr)\b[^>]*>)/g;
  for (const m of body.matchAll(re)) {
    const tag = m[1] || m[6];
    if (SEPARATED.test(tag)) continue;
    // Enough context to recognise the boundary again after unrelated edits,
    // but not so much that rewording one sentence churns its neighbours.
    const at = m.index;
    const left = body.slice(Math.max(0, at - 14), at).replace(/\s+/g, " ");
    const spaced = (m[2] || m[5]) === " ";
    const right = body.slice(at, at + m[0].length).replace(/\s+/g, " ");
    out.push(`${spaced ? "  " : "··"} ${left}${right}`);
  }
  return out;
}

// GETTING TO THE PROSE IS MOST OF THE WORK, because `"` is the busiest
// character in an HTML file and almost none of them are quotation marks. Every
// removal below is mechanical — it drops something that is not prose — and
// none of them decides anything about Korean.
//
//   comments      the generator strips them; readers never see them
//   <style>       CSS, and its /* */ comments hold English apostrophes
//   {% %} {{ }}   minijinja syntax: `{% include "footer.html" %}` is not a quote
//   tags          `class="btn"` is the overwhelming majority of every `"`
//
// JSON-LD is the exception and it is kept ON PURPOSE: issue #242 was two
// document names inside a <script>, where a page's own sources were quoted
// differently for machines than for people. So script bodies survive tag
// removal, and inside them the JSON's own structural `"` is ignored while an
// escaped `\"` — the only way a real double quotation can appear in JSON — is
// read as one.
const APOSTROPHE = /([A-Za-z])'([A-Za-z])/g;

function prose(html) {
  const body = html
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/<style\b[^>]*>[\s\S]*?<\/style>/g, "")
    .replace(/\{%[\s\S]*?%\}/g, "")
    .replace(/\{\{[\s\S]*?\}\}/g, "")
    .replace(/&ldquo;/g, "“")
    .replace(/&rdquo;/g, "”")
    .replace(/&lsquo;/g, "‘")
    .replace(/&rsquo;/g, "’")
    // `skill's` is a possessive, not an opening quote. Two Latin letters around
    // it is a fact about English spelling, not a judgement about Korean, and
    // without it every apostrophe in an English code sample pairs with the next
    // real quote and drags a paragraph into the ledger.
    .replace(APOSTROPHE, "$1ʼ$2");

  const out = [];
  let last = 0;
  for (const m of body.matchAll(/<script\b[^>]*>[\s\S]*?<\/script>/g)) {
    out.push({ script: false, text: body.slice(last, m.index).replace(/<[^>]*>/g, "") });
    out.push({ script: true, text: m[0].replace(/^<script\b[^>]*>/, "").replace(/<\/script>$/, "") });
    last = m.index + m[0].length;
  }
  out.push({ script: false, text: body.slice(last).replace(/<[^>]*>/g, "") });
  return out;
}

// One pass per mark rather than one alternation over all of them, so a nested
// pair is recorded too: `'새 agent에게 『이걸 해줘』라고'` is two decisions, and a
// single alternation records only the outer one.
//
// `script` is the form the mark takes inside a JSON-LD body, and only `""`
// differs: JSON spells a literal double quote `\"`, and its own structural `"`
// must not be read as prose. Every other mark is the same character in both
// places — which is the whole reason issue #242 was invisible until someone
// diffed the two by eye.
const MARKS = [
  { pair: '""', open: '"', close: '"', re: /"([^"]{1,160})"/g, script: /\\"([^"]{1,160})\\"/g },
  { pair: "''", open: "'", close: "'", re: /'([^']{1,160})'/g },
  { pair: "「」", open: "「", close: "」", re: /「([^「」]{1,160})」/g },
  { pair: "『』", open: "『", close: "』", re: /『([^『』]{1,160})』/g },
  { pair: "“”", open: "“", close: "”", re: /“([^“”]{1,160})”/g },
  { pair: "‘’", open: "‘", close: "’", re: /‘([^‘’]{1,160})’/g },
].map((m) => ({ script: m.re, ...m }));

// Long enough to tell two quotations of the same term apart, short enough that
// rewording the sentence after a quote does not churn its line.
const INNER = 44;
const LEFT = 16;

function quotes(html) {
  const out = [];
  for (const seg of prose(html)) {
    for (const mark of MARKS) {
      const re = seg.script ? mark.script : mark.re;
      if (!re) continue;
      for (const m of seg.text.matchAll(re)) {
        const left = seg.text
          .slice(Math.max(0, m.index - LEFT), m.index)
          .replace(/\s+/g, " ")
          .replace(/ʼ/g, "'");
        const inner = m[1].replace(/\s+/g, " ").replace(/ʼ/g, "'");
        const shown = inner.length > INNER ? `${inner.slice(0, INNER)}…` : inner;
        out.push(`${mark.pair}\t${left}${mark.open}${shown}${mark.close}`);
      }
    }
  }
  return out;
}

function collect(fn) {
  return fs
    .readdirSync(DIR)
    .filter((f) => f.endsWith(".html"))
    .sort()
    .flatMap((f) => fn(fs.readFileSync(path.join(DIR, f), "utf8")).map((b) => `${f}\t${b}`));
}

function readLedger(file) {
  if (!fs.existsSync(file)) return null;
  return fs
    .readFileSync(file, "utf8")
    .split("\n")
    .filter((l) => l && !l.startsWith("#"));
}

// Both ledgers are compared, and BOTH are reported before exiting. Stopping at
// the first difference would hide the other half of a change that moved
// spacing and quotes together — which is what editing one Korean sentence
// usually does.
function compare(name, file, now, hint) {
  const was = readLedger(file);
  if (!was) {
    console.log(`\n${path.basename(file)} is missing — run npm run ko:record`);
    return false;
  }
  const before = new Set(was);
  const after = new Set(now);
  const added = now.filter((l) => !before.has(l));
  const gone = was.filter((l) => !after.has(l));

  if (!added.length && !gone.length) {
    console.log(`\n${now.length} Korean ${name} decisions unchanged`);
    return true;
  }

  console.log("");
  for (const l of gone) console.log(`  was  ${l}`);
  for (const l of added) console.log(`  now  ${l}`);
  console.log(`\n${added.length} new or changed ${name} decision(s).\n${hint}`);
  return false;
}

function main() {
  const spacing = collect(boundaries);
  const quoted = collect(quotes);

  if (process.argv.includes("--record")) {
    fs.writeFileSync(SPACING, SPACING_HEADER + spacing.join("\n") + "\n");
    fs.writeFileSync(QUOTES, QUOTES_HEADER + quoted.join("\n") + "\n");
    console.log(
      `\nrecorded ${spacing.length} spacing boundaries and ${quoted.length} quoted passages across Korean pages`
    );
    return;
  }

  const ok = [
    compare(
      "spacing",
      SPACING,
      spacing,
      "Read them — `··` means glued, two spaces mean spaced. Re-record when they are right:\n  npm run ko:record"
    ),
    compare(
      "quote",
      QUOTES,
      quoted,
      "Read them — the second column is the mark someone chose. Re-record when they are right:\n  npm run ko:record"
    ),
  ];

  if (!ok.every(Boolean)) process.exitCode = 1;
}

if (require.main === module) main();

module.exports = { boundaries, quotes };
